---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/public_html
    - /bin/mkdir -p "$DEPLOYPATH/assets"
    - /bin/cp -f index.html "$DEPLOYPATH/"
    - /bin/cp -f *.css "$DEPLOYPATH/" 2>/dev/null || true
    - /bin/cp -f *.js "$DEPLOYPATH/" 2>/dev/null || true
    - /bin/cp -Rf assets/. "$DEPLOYPATH/assets/"
    - /bin/cp -f .htaccess "$DEPLOYPATH/" 2>/dev/null || true
    - /bin/rm -f "$DEPLOYPATH/assets/cases/LEIA-ME.txt"
